"use client";

import { useCallback, useEffect, useState } from "react";
import { useIsMobile } from "@/hooks/useIsMobile";

type AgentScope = "user" | "project";
type ThinkingLevel = "off" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
type Agent = { name: string; description: string; model?: string; thinkingLevel?: ThinkingLevel; tools?: string[]; skills?: string[]; mcp?: string[]; fallbackModels?: string[]; systemPromptMode?: "replace" | "append"; inheritProjectContext?: boolean; inheritSkills?: boolean; async?: boolean; timeoutMs?: number; systemPrompt: string; scope: AgentScope; filePath: string };
type Model = { id: string; name: string; provider: string };
type Skill = { name: string; description: string; filePath: string };

const TOOLS = ["read", "bash", "edit", "write", "grep", "find", "ls"];
const emptyForm = { name: "", description: "", model: "", thinkingLevel: "off" as ThinkingLevel, tools: [] as string[], skills: [] as string[], mcp: [] as string[], fallbackModels: [] as string[], systemPromptMode: "replace" as "replace" | "append", inheritProjectContext: false, inheritSkills: false, async: false, timeoutMs: 900000, systemPrompt: "", scope: "user" as AgentScope };
const THINKING_LABELS: Record<ThinkingLevel, string> = { off: "关闭", minimal: "极简", low: "低", medium: "中", high: "高", xhigh: "极高", max: "最大" };
const inputStyle: React.CSSProperties = { width: "100%", boxSizing: "border-box", padding: "10px 12px", borderRadius: 10, border: "1px solid var(--border)", background: "var(--bg-panel)", color: "var(--text)", fontSize: 12, outline: "none" };

function Spark({ small = false }: { small?: boolean }) {
  return <span style={{ width: small ? 28 : 42, height: small ? 28 : 42, display: "grid", placeItems: "center", borderRadius: small ? 8 : 12, background: "linear-gradient(135deg, color-mix(in srgb, var(--accent) 22%, transparent), color-mix(in srgb, #a855f7 18%, transparent))", color: "var(--accent)", flexShrink: 0 }}><svg width={small ? 14 : 20} height={small ? 14 : 20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M12 3l1.7 5.3L19 10l-5.3 1.7L12 17l-1.7-5.3L5 10l5.3-1.7L12 3z" /><path d="M19 16l.6 1.9L21.5 19l-1.9.6L19 21.5l-.6-1.9-1.9-.6 1.9-.6L19 16z" /></svg></span>;
}

function ChoiceSection({ title, description, items, selected, onToggle, empty }: { title: string; description: string; items: { id: string; label: string; detail?: string }[]; selected: string[]; onToggle: (id: string) => void; empty: string }) {
  const [query, setQuery] = useState("");
  const normalizedQuery = query.trim().toLowerCase();
  const visibleItems = items.filter((item) => !normalizedQuery || `${item.label} ${item.id} ${item.detail ?? ""}`.toLowerCase().includes(normalizedQuery));
  return <section style={{ marginTop: 14, padding: 14, border: "1px solid var(--border)", borderRadius: 14, background: "var(--bg-panel)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 8 }}><div><div style={{ fontSize: 12, fontWeight: 700 }}>{title}</div><div style={{ color: "var(--text-muted)", fontSize: 10, marginTop: 3 }}>{description}</div></div><span style={{ color: "var(--text-dim)", fontSize: 10 }}>{selected.length}/{items.length}</span></div>{items.length === 0 ? <div style={{ color: "var(--text-dim)", fontSize: 11 }}>{empty}</div> : <><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`搜索${title}…`} style={{ ...inputStyle, padding: "7px 9px", marginBottom: 8, fontSize: 11 }} /><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 6 }}>{visibleItems.map((item) => <button key={item.id} onClick={() => onToggle(item.id)} style={{ minWidth: 0, padding: "7px 9px", borderRadius: 8, border: `1px solid ${selected.includes(item.id) ? "color-mix(in srgb, var(--accent) 50%, var(--border))" : "var(--border)"}`, background: selected.includes(item.id) ? "color-mix(in srgb, var(--accent) 12%, var(--bg))" : "var(--bg)", color: selected.includes(item.id) ? "var(--accent)" : "var(--text-muted)", cursor: "pointer", textAlign: "left" }}><span style={{ display: "block", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 11 }}>{selected.includes(item.id) ? "✓ " : ""}{item.label}</span>{item.detail && <span style={{ display: "block", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap", fontSize: 9, color: "var(--text-dim)", marginTop: 2 }}>{item.detail}</span>}</button>)}{visibleItems.length === 0 && <div style={{ gridColumn: "1 / -1", color: "var(--text-dim)", fontSize: 11, padding: "6px 0" }}>没有匹配的项目</div>}</div></>}</section>;
}

export function SubagentsConfig({ cwd, onClose }: { cwd?: string | null; onClose: () => void }) {
  const isMobile = useIsMobile();
  const [agents, setAgents] = useState<Agent[]>([]); const [models, setModels] = useState<Model[]>([]); const [thinkingLevels, setThinkingLevels] = useState<Record<string, ThinkingLevel[]>>({}); const [skills, setSkills] = useState<Skill[]>([]); const [mcp, setMcp] = useState<string[]>([]);
  const [form, setForm] = useState(emptyForm); const [selected, setSelected] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const query = cwd ? `?cwd=${encodeURIComponent(cwd)}` : ""; const optionsQuery = cwd ? `?cwd=${encodeURIComponent(cwd)}&options=1` : ""; const [a, m, o] = await Promise.all([fetch(`/api/agents${query}`), fetch(`/api/models${query}`), cwd ? fetch(`/api/agents${optionsQuery}`) : Promise.resolve(null)]); const ad = await a.json() as { agents?: Agent[]; error?: string }; const md = await m.json() as { modelList?: Model[]; thinkingLevels?: Record<string, ThinkingLevel[]> }; if (!a.ok || ad.error) throw new Error(ad.error || "Unable to load agents"); setAgents(ad.agents ?? []); setModels(md.modelList ?? []); setThinkingLevels(md.thinkingLevels ?? {}); if (o) { const options = await o.json() as { skills?: Skill[]; mcp?: string[] }; setSkills(options.skills ?? []); setMcp(options.mcp ?? []); } } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setLoading(false); } }, [cwd]);
  useEffect(() => { void load(); }, [load]);
  const editAgent = (agent: Agent) => { setSelected(agent.filePath); setForm({ name: agent.name, description: agent.description, model: agent.model ?? "", thinkingLevel: agent.thinkingLevel ?? "off", tools: agent.tools ?? [], skills: agent.skills ?? [], mcp: agent.mcp ?? [], fallbackModels: agent.fallbackModels ?? [], systemPromptMode: agent.systemPromptMode ?? "replace", inheritProjectContext: agent.inheritProjectContext ?? false, inheritSkills: agent.inheritSkills ?? false, async: agent.async ?? false, timeoutMs: agent.timeoutMs ?? 900000, systemPrompt: agent.systemPrompt, scope: agent.scope }); setMessage(null); };
  const newAgent = () => { setSelected(null); setForm({ ...emptyForm, scope: cwd ? "project" : "user" }); setMessage(null); };
  const update = (key: string, value: unknown) => setForm((current) => ({ ...current, [key]: value }));
  const toggleTool = (tool: string) => setForm((current) => ({ ...current, tools: current.tools.includes(tool) ? current.tools.filter((item) => item !== tool) : [...current.tools, tool] }));
  const toggleChoice = (key: "skills" | "mcp", value: string) => setForm((current) => ({ ...current, [key]: current[key].includes(value) ? current[key].filter((item) => item !== value) : [...current[key], value] }));
  const save = async () => { setSaving(true); setMessage(null); try { const response = await fetch("/api/agents", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, cwd }) }); const data = await response.json() as { error?: string }; if (!response.ok || data.error) throw new Error(data.error || "Save failed"); await load(); setMessage("已保存"); } catch (error) { setMessage(error instanceof Error ? error.message : String(error)); } finally { setSaving(false); } };
  const remove = async () => { if (!form.name || !window.confirm(`Delete agent “${form.name}”?`)) return; const response = await fetch("/api/agents", { method: "DELETE", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, scope: form.scope, cwd }) }); if (!response.ok) { setMessage("删除失败"); return; } newAgent(); await load(); };

  return <div style={{ position: "fixed", inset: 0, zIndex: 1000, background: "rgba(9,12,24,0.54)", backdropFilter: "blur(10px)", display: "flex", alignItems: "center", justifyContent: "center", padding: 12 }} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div style={{ width: isMobile ? "100%" : 1040, height: isMobile ? "100%" : 700, maxWidth: "100%", maxHeight: "100%", background: "var(--bg)", border: "1px solid color-mix(in srgb, var(--border) 80%, var(--accent))", borderRadius: isMobile ? 16 : 22, display: "flex", flexDirection: "column", overflow: "hidden", boxShadow: "0 28px 100px rgba(0,0,0,.28)" }}>
      <header style={{ padding: isMobile ? "16px 18px" : "20px 26px", display: "flex", alignItems: "center", justifyContent: "space-between", borderBottom: "1px solid var(--border)", background: "radial-gradient(circle at 8% 0%, color-mix(in srgb, var(--accent) 15%, transparent), transparent 38%), var(--bg)" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}><Spark /><div><div style={{ fontSize: 17, fontWeight: 760, letterSpacing: "-0.02em" }}>Subagents</div><div style={{ color: "var(--text-muted)", fontSize: 11, marginTop: 3 }}>把重复工作交给合适的协作者</div></div></div>
        <button onClick={onClose} aria-label="关闭" style={{ width: 32, height: 32, border: "1px solid var(--border)", borderRadius: 10, background: "var(--bg-panel)", color: "var(--text-muted)", fontSize: 20, lineHeight: 1, cursor: "pointer" }}>×</button>
      </header>
      <div style={{ display: "flex", flex: 1, minHeight: 0, flexDirection: isMobile ? "column" : "row" }}>
        <aside style={{ width: isMobile ? "100%" : 300, flexShrink: 0, padding: 18, borderRight: isMobile ? "none" : "1px solid var(--border)", borderBottom: isMobile ? "1px solid var(--border)" : "none", overflow: "auto", background: "color-mix(in srgb, var(--bg-panel) 42%, var(--bg))" }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}><span style={{ fontSize: 10, fontWeight: 750, letterSpacing: ".12em", color: "var(--text-dim)" }}>AGENT LIBRARY</span><span style={{ fontSize: 10, color: "var(--text-muted)" }}>{agents.length} 个</span></div>
          <button onClick={newAgent} style={{ width: "100%", display: "flex", alignItems: "center", gap: 9, padding: "11px 12px", marginBottom: 12, border: "1px solid color-mix(in srgb, var(--accent) 38%, var(--border))", borderRadius: 11, background: "color-mix(in srgb, var(--accent) 10%, var(--bg))", color: "var(--accent)", fontWeight: 700, cursor: "pointer", textAlign: "left" }}><span style={{ fontSize: 18, lineHeight: 1 }}>＋</span>新建 Subagent</button>
          {loading ? <div style={{ color: "var(--text-muted)", fontSize: 12, padding: 8 }}>正在载入…</div> : agents.length === 0 ? <div style={{ padding: "20px 8px", color: "var(--text-dim)", fontSize: 12, lineHeight: 1.7 }}>还没有协作者。<br />创建一个角色，让它拥有清晰的职责和边界。</div> : agents.map((agent) => <button key={agent.filePath} onClick={() => editAgent(agent)} style={{ width: "100%", display: "flex", gap: 10, textAlign: "left", padding: 10, marginBottom: 6, border: selected === agent.filePath ? "1px solid color-mix(in srgb, var(--accent) 45%, var(--border))" : "1px solid transparent", borderRadius: 12, background: selected === agent.filePath ? "color-mix(in srgb, var(--accent) 10%, var(--bg))" : "transparent", color: "var(--text)", cursor: "pointer" }}><Spark small /><span style={{ minWidth: 0, flex: 1 }}><span style={{ display: "block", fontWeight: 700, fontSize: 12 }}>{agent.name}</span><span style={{ display: "block", color: "var(--text-muted)", fontSize: 11, marginTop: 3, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{agent.description}</span><span style={{ display: "block", color: "var(--text-dim)", fontSize: 10, marginTop: 5 }}>{agent.scope === "project" ? "项目" : "全局"} · {agent.model || "默认模型"}</span></span></button>)}
        </aside>
        <main style={{ flex: 1, minWidth: 0, padding: isMobile ? 16 : "24px 30px", overflow: "auto" }}>
          <div style={{ position: "sticky", top: isMobile ? -16 : -24, zIndex: 5, display: "flex", justifyContent: "flex-end", gap: 8, margin: isMobile ? "-16px -16px 18px" : "-24px -30px 18px", padding: "10px 30px", borderBottom: "1px solid var(--border)", background: "color-mix(in srgb, var(--bg) 92%, transparent)", backdropFilter: "blur(12px)" }}>
            <button onClick={() => void save()} disabled={saving || !form.name || !form.description} style={{ padding: "8px 14px", border: "none", borderRadius: 9, background: "linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 70%, #a855f7))", color: "white", fontWeight: 700, cursor: "pointer", opacity: saving || !form.name || !form.description ? .5 : 1 }}>{saving ? "保存中…" : "保存配置"}</button>
            {selected && <button onClick={() => void remove()} style={{ padding: "7px 12px", border: "1px solid color-mix(in srgb, #ef4444 55%, var(--border))", borderRadius: 9, background: "transparent", color: "#ef4444", cursor: "pointer" }}>删除</button>}
            {message && <span style={{ alignSelf: "center", fontSize: 11, color: message === "已保存" ? "var(--accent)" : "#ef4444" }}>{message}</span>}
          </div>
          <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 20, marginBottom: 22 }}><div><div style={{ color: "var(--accent)", fontSize: 10, fontWeight: 750, letterSpacing: ".12em", marginBottom: 6 }}>{selected ? "EDIT AGENT" : "NEW AGENT"}</div><h2 style={{ margin: 0, fontSize: 22, letterSpacing: "-0.03em" }}>{selected ? `编辑 ${form.name}` : "创建一个专属协作者"}</h2><p style={{ margin: "7px 0 0", color: "var(--text-muted)", fontSize: 12 }}>先定义它做什么，再决定它能看到什么。</p></div><div style={{ padding: "7px 10px", borderRadius: 999, background: "var(--bg-panel)", color: "var(--text-muted)", fontSize: 10, whiteSpace: "nowrap" }}>Markdown agent</div></div>
          <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 16 }}>
            <label style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>名称<input value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="researcher" style={{ ...inputStyle, marginTop: 6 }} /></label>
            <label style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>一句话职责<input value={form.description} onChange={(e) => update("description", e.target.value)} placeholder="负责资料检索和事实核查" style={{ ...inputStyle, marginTop: 6 }} /></label>
            <div><label style={{ display: "block", fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>模型<select value={form.model} onChange={(e) => update("model", e.target.value)} style={{ ...inputStyle, marginTop: 6 }}><option value="">使用默认模型</option>{models.map((model) => <option key={`${model.provider}/${model.id}`} value={`${model.provider}/${model.id}`}>{model.name || model.id} ({model.provider})</option>)}</select></label><label style={{ display: "block", marginTop: 12, fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>思考强度<select value={form.thinkingLevel} onChange={(e) => update("thinkingLevel", e.target.value)} style={{ ...inputStyle, marginTop: 6 }}><option value="off">关闭</option>{(thinkingLevels[form.model.replace("/", ":")] ?? ["minimal", "low", "medium", "high", "xhigh", "max"] as ThinkingLevel[]).filter((level) => level !== "off").map((level) => <option key={level} value={level}>{THINKING_LABELS[level]}</option>)}</select></label></div>
            <div><div style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 600, marginBottom: 6 }}>作用域</div><div style={{ display: "flex", gap: 6 }}><button onClick={() => update("scope", "user")} style={{ ...inputStyle, width: "auto", flex: 1, cursor: "pointer", background: form.scope === "user" ? "color-mix(in srgb, var(--accent) 13%, var(--bg-panel))" : "var(--bg-panel)", borderColor: form.scope === "user" ? "var(--accent)" : "var(--border)", color: form.scope === "user" ? "var(--accent)" : "var(--text-muted)" }}>全局</button><button onClick={() => cwd && update("scope", "project")} disabled={!cwd} style={{ ...inputStyle, width: "auto", flex: 1, cursor: cwd ? "pointer" : "not-allowed", opacity: cwd ? 1 : .45, background: form.scope === "project" ? "color-mix(in srgb, var(--accent) 13%, var(--bg-panel))" : "var(--bg-panel)", borderColor: form.scope === "project" ? "var(--accent)" : "var(--border)", color: form.scope === "project" ? "var(--accent)" : "var(--text-muted)" }}>项目</button></div></div>
          </div>
          <section style={{ marginTop: 16, padding: 14, border: "1px solid var(--border)", borderRadius: 14, background: "var(--bg-panel)" }}>
            <div style={{ fontSize: 12, fontWeight: 700 }}>运行方式与上下文</div>
            <div style={{ color: "var(--text-muted)", fontSize: 10, marginTop: 3, marginBottom: 10 }}>这些设置直接对应 pi-subagents 的 Agent 配置。</div>
            <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "1fr 1fr", gap: 12 }}>
              <label style={{ fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>备用模型（每行一个）<textarea value={form.fallbackModels.join("\n")} onChange={(e) => update("fallbackModels", e.target.value.split(/\n|,/).map((value) => value.trim()).filter(Boolean))} placeholder="openai/gpt-5-mini" rows={3} style={{ ...inputStyle, marginTop: 6, resize: "vertical", fontFamily: "var(--font-mono)", fontSize: 11 }} /></label>
              <div>
                <label style={{ display: "block", fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>超时时间（毫秒）<input type="number" min={1000} step={1000} value={form.timeoutMs} onChange={(e) => update("timeoutMs", Number(e.target.value) || 900000)} style={{ ...inputStyle, marginTop: 6 }} /></label>
                <label style={{ display: "flex", alignItems: "center", gap: 8, marginTop: 12, fontSize: 11, color: "var(--text-muted)", cursor: "pointer" }}><input type="checkbox" checked={form.async} onChange={(e) => update("async", e.target.checked)} />默认后台运行</label>
              </div>
            </div>
            <div style={{ display: "flex", flexWrap: "wrap", gap: 8, marginTop: 12 }}>
              <label style={{ display: "flex", alignItems: "center", gap: 7, padding: "7px 9px", border: "1px solid var(--border)", borderRadius: 8, fontSize: 11, color: "var(--text-muted)", cursor: "pointer" }}><input type="checkbox" checked={form.inheritProjectContext} onChange={(e) => update("inheritProjectContext", e.target.checked)} />继承项目上下文</label>
              <label style={{ display: "flex", alignItems: "center", gap: 7, padding: "7px 9px", border: "1px solid var(--border)", borderRadius: 8, fontSize: 11, color: "var(--text-muted)", cursor: "pointer" }}><input type="checkbox" checked={form.inheritSkills} onChange={(e) => update("inheritSkills", e.target.checked)} />继承技能目录</label>
              <label style={{ display: "flex", alignItems: "center", gap: 7, padding: "7px 9px", border: "1px solid var(--border)", borderRadius: 8, fontSize: 11, color: "var(--text-muted)", cursor: "pointer" }}>System Prompt<select value={form.systemPromptMode} onChange={(e) => update("systemPromptMode", e.target.value)} style={{ border: "none", background: "transparent", color: "var(--text)", fontSize: 11 }}><option value="replace">替换</option><option value="append">追加</option></select></label>
            </div>
          </section>
          <section style={{ marginTop: 22, padding: 14, border: "1px solid var(--border)", borderRadius: 14, background: "var(--bg-panel)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 10 }}><div><div style={{ fontSize: 12, fontWeight: 700 }}>工具权限</div><div style={{ color: "var(--text-muted)", fontSize: 10, marginTop: 3 }}>只开放完成职责所需的能力</div></div><span style={{ color: "var(--text-dim)", fontSize: 10 }}>{form.tools.length}/{TOOLS.length} enabled</span></div><div style={{ display: "flex", flexWrap: "wrap", gap: 7 }}>{TOOLS.map((tool) => <button key={tool} onClick={() => toggleTool(tool)} style={{ padding: "6px 10px", borderRadius: 8, border: `1px solid ${form.tools.includes(tool) ? "color-mix(in srgb, var(--accent) 50%, var(--border))" : "var(--border)"}`, background: form.tools.includes(tool) ? "color-mix(in srgb, var(--accent) 14%, var(--bg))" : "var(--bg)", color: form.tools.includes(tool) ? "var(--accent)" : "var(--text-muted)", fontSize: 11, cursor: "pointer" }}>{form.tools.includes(tool) ? "✓ " : ""}{tool}</button>)}</div></section>
          <ChoiceSection title="可用技能" description="只让该 Subagent 调用选中的技能" items={skills.map((skill) => ({ id: skill.name, label: skill.name, detail: skill.description }))} selected={form.skills} onToggle={(id) => toggleChoice("skills", id)} empty="当前项目暂无可用技能" />
          <ChoiceSection title="MCP 工具" description="控制该 Subagent 可以使用的 MCP Server" items={mcp.map((server) => ({ id: server, label: server }))} selected={form.mcp} onToggle={(id) => toggleChoice("mcp", id)} empty="当前未发现 MCP Server" />
          <label style={{ display: "block", marginTop: 22, fontSize: 11, color: "var(--text-muted)", fontWeight: 600 }}>System Prompt<textarea value={form.systemPrompt} onChange={(e) => update("systemPrompt", e.target.value)} placeholder="你是一名专业的研究员……\n\n工作方式：\n- 先列出事实和来源\n- 明确标记待核验内容" rows={isMobile ? 8 : 10} style={{ ...inputStyle, marginTop: 6, resize: "vertical", fontFamily: "var(--font-mono)", lineHeight: 1.65 }} /></label>
          <div style={{ display: "flex", alignItems: "center", gap: 9, marginTop: 22, paddingTop: 16, borderTop: "1px solid var(--border)" }}><button onClick={() => void save()} disabled={saving || !form.name || !form.description} style={{ padding: "10px 18px", border: "none", borderRadius: 10, background: "linear-gradient(135deg, var(--accent), color-mix(in srgb, var(--accent) 70%, #a855f7))", color: "white", fontWeight: 700, cursor: "pointer", opacity: saving || !form.name || !form.description ? .5 : 1 }}>{saving ? "保存中…" : "保存配置"}</button>{selected && <button onClick={() => void remove()} style={{ padding: "9px 14px", border: "1px solid color-mix(in srgb, #ef4444 55%, var(--border))", borderRadius: 10, background: "transparent", color: "#ef4444", cursor: "pointer" }}>删除</button>}{message && <span style={{ fontSize: 11, color: message === "已保存" ? "var(--accent)" : "#ef4444" }}>{message}</span>}</div>
        </main>
      </div>
    </div>
  </div>;
}
