"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { useIsMobile } from "@/hooks/useIsMobile";

type Status = "backlog" | "active" | "done";
type Task = { id: string; title: string; detail: string; agent: string; status: Status; createdAt: string; output?: string; error?: string };
type Agent = { name: string; description: string; scope: "user" | "project" };
const columns: Array<{ id: Status; label: string; hint: string }> = [
  { id: "backlog", label: "待处理", hint: "准备分配" }, { id: "active", label: "执行中", hint: "正在工作" }, { id: "done", label: "已完成", hint: "留下结果" },
];

export function TaskBoard({ cwd, onClose }: { cwd: string; onClose: () => void }) {
  const isMobile = useIsMobile();
  const [tasks, setTasks] = useState<Task[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [selected, setSelected] = useState<Task | null>(null);
  const [title, setTitle] = useState(""); const [detail, setDetail] = useState(""); const [agent, setAgent] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const query = `?cwd=${encodeURIComponent(cwd)}`; const [board, agentResponse] = await Promise.all([fetch(`/api/board${query}`), fetch(`/api/agents${query}`)]); const boardData = await board.json() as { tasks?: Task[]; error?: string }; const agentData = await agentResponse.json() as { agents?: Agent[] }; if (!board.ok || boardData.error) throw new Error(boardData.error || "无法载入看板"); setTasks(boardData.tasks ?? []); setAgents(agentData.agents ?? []); if (!agent && agentData.agents?.[0]) setAgent(agentData.agents[0].name); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }, [cwd, agent]);
  useEffect(() => { void load(); }, [load]);
  const create = async () => { if (!title.trim() || !agent) return; setBusy(true); setError(null); try { const response = await fetch("/api/board", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cwd, title, detail, agent }) }); const data = await response.json() as { task?: Task; error?: string }; if (!response.ok) throw new Error(data.error || "创建失败"); setTasks((current) => [data.task!, ...current]); setTitle(""); setDetail(""); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } };
  const run = async (task: Task) => { setBusy(true); setError(null); setTasks((current) => current.map((item) => item.id === task.id ? { ...item, status: "active" } : item)); try { const response = await fetch("/api/board", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ cwd, action: "run", id: task.id }) }); const data = await response.json() as { task?: Task; error?: string }; if (!response.ok) throw new Error(data.error || "执行失败"); setTasks((current) => current.map((item) => item.id === task.id ? data.task! : item)); setSelected(data.task!); } catch (e) { setError(e instanceof Error ? e.message : String(e)); await load(); } finally { setBusy(false); } };
  const grouped = useMemo(() => Object.fromEntries(columns.map((column) => [column.id, tasks.filter((task) => task.status === column.id)])) as Record<Status, Task[]>, [tasks]);

  return <div style={{ position: "fixed", inset: 0, zIndex: 1000, padding: 12, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(35,23,25,.56)", backdropFilter: "blur(8px)" }} onClick={(event) => { if (event.target === event.currentTarget) onClose(); }}>
    <div style={{ width: isMobile ? "100%" : 1120, height: isMobile ? "100%" : 720, maxWidth: "100%", maxHeight: "100%", display: "flex", flexDirection: "column", overflow: "hidden", border: "1px solid var(--border)", borderRadius: 18, background: "var(--bg)", boxShadow: "0 30px 100px rgba(30,20,20,.3)" }}>
      <header style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 12, padding: "18px 22px", borderBottom: "1px solid var(--border)", background: "var(--bg-panel)" }}><div><div style={{ fontSize: 10, letterSpacing: ".14em", color: "var(--accent)", fontWeight: 750 }}>MJU / TASK BOARD</div><h2 style={{ margin: "5px 0 0", fontFamily: "Georgia, serif", fontSize: 22 }}>任务看板</h2><div style={{ marginTop: 4, fontSize: 11, color: "var(--text-muted)" }}>把任务交给合适的 Agent，结果会留在项目看板里。</div></div><button onClick={onClose} style={{ width: 32, height: 32, border: "1px solid var(--border)", borderRadius: 9, background: "transparent", color: "var(--text-muted)", fontSize: 20, cursor: "pointer" }}>×</button></header>
      <div style={{ display: "flex", flex: 1, minHeight: 0, flexDirection: isMobile ? "column" : "row" }}>
        <section style={{ width: isMobile ? "100%" : 270, flexShrink: 0, padding: 18, overflow: "auto", borderRight: isMobile ? "none" : "1px solid var(--border)", borderBottom: isMobile ? "1px solid var(--border)" : "none" }}><div style={{ fontSize: 10, color: "var(--text-dim)", fontWeight: 750, letterSpacing: ".12em", marginBottom: 12 }}>NEW TASK</div><label style={{ display: "block", fontSize: 11, color: "var(--text-muted)", fontWeight: 650 }}>任务名称<input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="整理合同审查意见" style={{ width: "100%", boxSizing: "border-box", marginTop: 6, padding: "9px 10px", border: "1px solid var(--border)", borderRadius: 9, background: "var(--bg-panel)", color: "var(--text)" }} /></label><label style={{ display: "block", marginTop: 14, fontSize: 11, color: "var(--text-muted)", fontWeight: 650 }}>分配给<select value={agent} onChange={(e) => setAgent(e.target.value)} style={{ width: "100%", marginTop: 6, padding: "9px 10px", border: "1px solid var(--border)", borderRadius: 9, background: "var(--bg-panel)", color: "var(--text)" }}><option value="">先创建 Subagent</option>{agents.map((item) => <option key={item.name} value={item.name}>{item.name} · {item.scope === "project" ? "项目" : "全局"}</option>)}</select></label><label style={{ display: "block", marginTop: 14, fontSize: 11, color: "var(--text-muted)", fontWeight: 650 }}>任务说明<textarea value={detail} onChange={(e) => setDetail(e.target.value)} rows={6} placeholder="补充目标、材料、交付格式……" style={{ width: "100%", boxSizing: "border-box", marginTop: 6, padding: "9px 10px", resize: "vertical", border: "1px solid var(--border)", borderRadius: 9, background: "var(--bg-panel)", color: "var(--text)", lineHeight: 1.5 }} /></label><button onClick={() => void create()} disabled={busy || !title.trim() || !agent} style={{ width: "100%", marginTop: 14, padding: "10px 12px", border: 0, borderRadius: 9, background: "var(--accent)", color: "#fff", fontWeight: 700, cursor: "pointer", opacity: busy || !title.trim() || !agent ? .45 : 1 }}>加入看板</button>{agents.length === 0 && <div style={{ marginTop: 12, color: "var(--text-muted)", fontSize: 11, lineHeight: 1.6 }}>还没有可用 Agent。请先在 Agents 中创建角色配置。</div>}{error && <div style={{ marginTop: 12, color: "#a42f3e", fontSize: 11, lineHeight: 1.5 }}>{error}</div>}</section>
        <section style={{ flex: 1, minWidth: 0, minHeight: 0, padding: 18, overflow: "auto" }}>
          {loading ? <div style={{ color: "var(--text-muted)", fontSize: 12 }}>正在载入看板…</div> : <div style={{ display: "grid", gridTemplateColumns: isMobile ? "1fr" : "repeat(3, minmax(190px, 1fr))", gap: 12, alignItems: "start" }}>{columns.map((column) => <div key={column.id} style={{ minHeight: 160, padding: 10, border: "1px solid var(--border)", borderRadius: 12, background: "color-mix(in srgb, var(--bg-panel) 55%, var(--bg))" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "3px 4px 10px" }}><div><div style={{ fontWeight: 700, fontSize: 12 }}>{column.label}</div><div style={{ color: "var(--text-dim)", fontSize: 10, marginTop: 2 }}>{column.hint}</div></div><span style={{ color: "var(--text-muted)", fontSize: 10 }}>{grouped[column.id].length}</span></div>{grouped[column.id].map((task) => <article key={task.id} onClick={() => setSelected(task)} style={{ marginTop: 7, padding: 11, border: "1px solid var(--border)", borderRadius: 10, background: "var(--bg)", cursor: "pointer" }}><div style={{ fontSize: 12, fontWeight: 700, lineHeight: 1.4 }}>{task.title}</div><div style={{ marginTop: 7, color: "var(--accent)", fontSize: 10 }}>↗ {task.agent}</div>{task.status === "backlog" && <button onClick={(event) => { event.stopPropagation(); void run(task); }} disabled={busy} style={{ width: "100%", marginTop: 9, padding: "6px 8px", border: "1px solid var(--border)", borderRadius: 7, background: "var(--bg-panel)", color: "var(--text)", fontSize: 10, cursor: "pointer" }}>运行任务</button>}{task.status === "active" && <div style={{ marginTop: 9, color: "var(--accent)", fontSize: 10 }}>正在执行…</div>}</article>)}</div>)}</div>}
        </section>
      </div>
      {selected && <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", padding: 18, background: "rgba(35,23,25,.3)" }} onClick={(event) => { if (event.target === event.currentTarget) setSelected(null); }}><div style={{ width: isMobile ? "100%" : 620, maxHeight: "80%", overflow: "auto", padding: 20, border: "1px solid var(--border)", borderRadius: 14, background: "var(--bg)", boxShadow: "0 20px 70px rgba(0,0,0,.2)" }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><div style={{ color: "var(--accent)", fontSize: 10, letterSpacing: ".1em" }}>{selected.agent}</div><h3 style={{ margin: "6px 0 0", fontFamily: "Georgia, serif", fontSize: 20 }}>{selected.title}</h3></div><button onClick={() => setSelected(null)} style={{ border: 0, background: "transparent", color: "var(--text-muted)", fontSize: 19, cursor: "pointer" }}>×</button></div><p style={{ color: "var(--text-muted)", fontSize: 12, lineHeight: 1.7, whiteSpace: "pre-wrap" }}>{selected.detail || "没有补充说明"}</p>{selected.output && <pre style={{ margin: 0, padding: 12, overflow: "auto", border: "1px solid var(--border)", borderRadius: 9, background: "var(--bg-panel)", color: "var(--text)", fontFamily: "var(--font-mono)", fontSize: 11, lineHeight: 1.6, whiteSpace: "pre-wrap" }}>{selected.output}</pre>}{selected.error && <div style={{ color: "#a42f3e", fontSize: 12 }}>{selected.error}</div>}</div></div>}
    </div>
  </div>;
}
